apiVersion: v2
appVersion: "11.2"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version:  12.14.2
deprecated: false
description: Technitium DNS Server is an open source authoritative as well as recursive DNS server that can be used for self hosting a DNS server for privacy & security.
home: https://truecharts.org/charts/incubator/technitium
icon: https://truecharts.org/img/hotlink-ok/chart-icons/technitium.png
keywords:
  - DNS
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: technitium
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/technitium
  - https://github.com/TechnitiumSoftware/DnsServer
  - https://technitium.com/
type: application
version: 4.0.0
annotations:
  truecharts.org/catagories: |
    - networking
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
  artifacthub.io/changes:  Migrate from v8.1 to v11.2, adopt new TrueNAS common and QUIC
